### ISSUE TITLE
Problem loading SE Resnext pretrained model

### ISSUE THREAD

**Issue by Karthik-Suresh93** [Cadene/pretrained-models.pytorch#115]
I tried to load the imagenet pretrained SE Resnext model (50 and 101). Both give the following error:

`>>> pretrainedmodels.__version__`
'0.7.4'

`>>>model_name = 'se_resnext101_32x4d'`
`>>> model = pretrainedmodels.__dict__[model_name](num_classes=1000, pretrained='imagenet')`

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ksuresh/.conda/envs/pytorch0.3/lib/python2.7/site-packages/pretrainedmodels/models/senet.py", line 438, in se_resnext101_32x4d
    num_classes=num_classes)
  File "/home/ksuresh/.conda/envs/pytorch0.3/lib/python2.7/site-packages/pretrainedmodels/models/senet.py", line 291, in __init__
    downsample_padding=0
  File "/home/ksuresh/.conda/envs/pytorch0.3/lib/python2.7/site-packages/pretrainedmodels/models/senet.py", line 340, in _make_layer
    downsample))
  File "/home/ksuresh/.conda/envs/pytorch0.3/lib/python2.7/site-packages/pretrainedmodels/models/senet.py", line 194, in __init__
    stride=1)
  File "/home/ksuresh/.conda/envs/pytorch0.3/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 278, in __init__
    False, _pair(0), groups, bias)
  File "/home/ksuresh/.conda/envs/pytorch0.3/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 33, in __init__
    out_channels, in_channels // groups, *kernel_size))
TypeError: torch.FloatTensor constructor received an invalid combination of arguments - got (float, int, int, int), but expected one of:
 * no arguments
 * (int ...)
      didn't match because some of the arguments have invalid types: (float, int, int, int)
 * (torch.FloatTensor viewed_tensor)
 * (torch.Size size)
 * (torch.FloatStorage data)
 * (Sequence data)

Could you please tell me what the issue is?

**Comment by ZHOUXINWEN** [comment]
Do you have solved this problem? I meet the same problem.
And I fixed it by replacing the 192 line ` width = math.floor(planes * (base_width / 64)) * groups`  with `width = int((planes * (float(base_width) / 64)) * groups)`
