### ISSUE TITLE
Installation Failure with EOFError

### ISSUE THREAD

**Issue by fengluxu** [Cadene/pretrained-models.pytorch#121]
I tried to install this package from repo but got EOF error from runing
python setup.py install

Could you help me to figure it out?

ERROR:
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from setuptools import setup, find_packages
  File "/home/feng/anaconda3/envs/ECO/lib/python3.5/site-packages/setuptools/__init__.py", line 14, in <module>
    import setuptools.version
  File "/home/feng/anaconda3/envs/ECO/lib/python3.5/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/home/feng/anaconda3/envs/ECO/lib/python3.5/site-packages/pkg_resources/__init__.py", line 82, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/home/feng/anaconda3/envs/ECO/lib/python3.5/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/fengluxu/anaconda3/envs/ECO/lib/python3.5/site-packages/pkg_resources/extern/__init__.py", line 43, in load_module
    __import__(extant)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 765, in get_code
  File "<frozen importlib._bootstrap_external>", line 476, in _compile_bytecode
EOFError: marshal data too short

**Comment by sherrylzy** [comment]
Hi, I meet the same problem. Do you solve this problem?
