### ISSUE TITLE
RuntimeError: Expected object of backend CPU but got backend CUDA for argument #2 'weight'

### ISSUE THREAD

**Issue by marsggbo** [Cadene/pretrained-models.pytorch#135]
```Traceback (most recent call last):
  File "select_100classes.py", line 114, in <module>
    main()
  File "select_100classes.py", line 68, in main
    outputs = model(inputs)
  File "D:\Continuum\anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Continuum\anaconda3\envs\py36\lib\site-packages\pretrainedmodels\models\pnasnet.py", line 367, in forward
    x = self.features(input)
  File "D:\Continuum\anaconda3\envs\py36\lib\site-packages\pretrainedmodels\models\pnasnet.py", line 341, in features

    x_conv_0 = self.conv_0(x)
  File "D:\Continuum\anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Continuum\anaconda3\envs\py36\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "D:\Continuum\anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Continuum\anaconda3\envs\py36\lib\site-packages\torch\nn\modules\conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected object of backend CPU but got backend CUDA for argument #2 'weight'
```

**Comment by Cadene** [comment]
input = input.cuda()
net.cuda()

net(input)
