### ISSUE TITLE
couldnot use inception_resnetv2

### ISSUE THREAD

**Issue by dsd009** [Cadene/pretrained-models.pytorch#136]
Traceback (most recent call last):
  File "clas_inc_res.py", line 299, in <module>
    model_conv.classifier._modules["1"] = nn.Conv2d(512, num_of_output_classes, kernel_size=(1, 1))
  File "/home/raman/anaconda2/envs/pyto3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'InceptionResNetV2' object has no attribute 'classifier'

**Comment by PPPW** [comment]
Hi, the API was changed in 12/02/2017 (see commit “Improve API”). You can change “classifier” into “logits”
