### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by ooodragon94** [Cadene/pretrained-models.pytorch#192]
hello, trying to use inceptionv4
a long, unprecedented error shown to me..

```
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=278 error=700 : an illegal memory access was encountered
Traceback (most recent call last):
  File "main.py", line 605, in <module>
    main()
  File "main.py", line 166, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 366, in main_worker
    train_kd(train_loader, teacher, model, criterion, optimizer, epoch, args)
  File "main.py", line 415, in train_kd
    o_teacher = Variable(teacher(images), requires_grad=False)
  File "/home/USER/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/USER/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/USER/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/USER/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/USER/.local/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
```

and than it goes on..

```
Original Traceback (most recent call last):
  File "/home/USER/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/USER/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/USER/.local/lib/python3.6/site-packages/pretrainedmodels/models/inceptionv4.py", line 307, in forward
    x = self.features(input)
  File "/home/USER/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/USER/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/USER/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/USER/.local/lib/python3.6/site-packages/pretrainedmodels/models/inceptionv4.py", line 87, in forward
    x1 = self.branch1(x)
  File "/home/USER/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/USER/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/USER/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/USER/.local/lib/python3.6/site-packages/pretrainedmodels/models/inceptionv4.py", line 50, in forward
    x = self.relu(x)
  File "/home/USER/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/USER/.local/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 94, in forward
    return F.relu(input, inplace=self.inplace)
  File "/home/USER/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1061, in relu
    result = torch.relu_(input)   
RuntimeError: CUDA error: an illegal memory access was encountered

terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:771)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7f293ae2b536 in /home/USER/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x7ae (0x7f293b06efbe in /home/USER/.local/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f293ae1babd in /home/USER/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x523142 (0x7f29380c3142 in /home/USER/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x5231e6 (0x7f29380c31e6 in /home/USER/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: python3() [0x54ef16]
frame #6: python3() [0x54ec1b]
frame #7: python3() [0x54ec1b]
frame #8: python3() [0x588948]
frame #9: python3() [0x5ad438]
frame #10: python3() [0x5ad44e]   
frame #11: python3() [0x5ad44e]   
frame #12: python3() [0x5ad44e]   
frame #13: python3() [0x5ad44e]   
frame #14: python3() [0x5ad44e]   
frame #15: python3() [0x56b276]   
<omitting python frames>
frame #21: __libc_start_main + 0xe7 (0x7f2945bdab97 in /lib/x86_64-linux-gnu/libc.so.6)

```

any idea or suggestions? help me please!!

**Comment by ooodragon94** [comment]
seems like my graphic cards were failing
it wouldn't fit batches that it did before
lowering down did fix it but I think there will be better solutions
