### ISSUE TITLE
Example imagenet_eval.py giving error

### ISSUE THREAD

**Issue by eyildiz-ugoe** [Cadene/pretrained-models.pytorch#77]
Launching:

`python3 imagenet_eval.py --data ../data`

Getting:

```
=> creating model 'nasnetamobile'
=> using pre-trained parameters 'imagenet'
Images transformed from size 256 to [3, 224, 224]
Traceback (most recent call last):
  File "imagenet_eval.py", line 304, in <module>
    main()
  File "imagenet_eval.py", line 124, in main
    datasets.ImageFolder(valdir, val_tf),
  File "/usr/local/lib/python3.5/dist-packages/torchvision/datasets/folder.py", line 178, in __init__
    target_transform=target_transform)
  File "/usr/local/lib/python3.5/dist-packages/torchvision/datasets/folder.py", line 79, in __init__
    "Supported extensions are: " + ",".join(extensions)))
RuntimeError: Found 0 files in subfolders of: ../data/val

```

Any idea why this happens? (I do have a data/val folder with a cat image (.jpg) in it for inference.)

**Comment by densechen** [comment]
How do you fix this?
